source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby '2.5.3'

gem 'rails', '5.2.1'

gem 'active_scheduler', '0.5.0'
gem 'faraday', '0.15.3'
gem 'figaro', '1.1.1'
gem 'hiredis', '0.6.1'
gem 'puma', '3.12.3'
gem 'redis', '3.3.5', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.27.4'
gem 'resque-pool', '0.6.0'
gem 'sass-rails', '5.0.7'
gem 'sprockets-es6', '0.9.2'
gem 'pg', '0.21.0'
gem 'uglifier', '4.1.19'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'capybara'
  gem 'factory_bot_rails', '4.11.1'
  gem 'poltergeist', '1.18.1'
  gem 'rspec-rails', '3.8.1'
  gem 'timecop'
  gem 'vcr'
end