source 'https://rubygems.org'

ruby '2.2.3'

gem 'rails', '4.2.5'

# Assets
gem 'sass', '~> 3.4.11'
gem 'sass-rails', '5.0.3'
gem 'uglifier', '>= 2.7.1'
gem 'coffee-rails', '~> 4.1.0'

gem 'pg', '0.18.4'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'figaro', '1.1.1'

# Application Server
gem 'unicorn', '4.9.0'

group :development, :test do
  gem 'rspec-rails', '3.3.2'
  gem 'guard-rspec', '~> 4.6.0'
  gem 'factory_girl_rails', '4.5.0'
  gem 'capybara', '2.4.4'
  gem 'poltergeist', '1.6.0'
  gem 'pry'
  gem 'pry-remote'
  gem 'quiet_assets'
  gem 'database_cleaner', '~> 1.4.1'
  gem 'unicorn-rails'
end
