source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.1.7'
gem 'tzinfo-data', '>= 1.2020.6'  # Don't rely on OSX/Linux timezone data

# Drivers
gem 'elasticsearch', '7.17.1'
# gem 'hiredis-client', '0.10.0' # for Redis > 5
gem 'hiredis', '0.6.3'
gem 'mini_magick', '4.11.0'
gem 'pg', '1.4.4'
# Upgrade to > 5 after Rails 7.0.4, because Actioncable requires Redis < 5 before that point.
# gem 'redis', '5.0.4'
gem 'redis', '4.7.1', require: ['redis', 'redis/connection/hiredis']
gem 'typhoeus', '1.4.0'

# JavaScript and assets
gem 'autoprefixer-rails', '10.4.7.0'
gem 'bootstrap_form', '5.1.0'
gem 'bootstrap4-kaminari-views', '1.0.1'
gem 'sass-rails', '6.0.0'
gem 'webpacker', '5.4.3'

# Jobs
gem 'active_scheduler', '0.7.0'
gem 'resque', '2.0.0'
gem 'resque-pool', github: 'nevans/resque-pool' # once version after 0.7.1 is released, go back
gem 'resque-scheduler', '4.4.0'
gem 'sinatra', github: 'sinatra/sinatra'

# Logging/instrumentation
# gem 'full_request_logger', github: 'basecamp/full_request_logger'

# Monitoring
gem 'easymon', '1.6.2'
# gem 'sentry-raven', '3.1.1'

# Profiling/troubleshooting
gem 'rbtrace', '0.4.14'
gem 'stackprof', '0.2.22'
gem 'rack-mini-profiler', '3.0.0', require: false
gem 'flamegraph', '0.9.5'

# Security
gem 'devise', '4.8.1'
# gem 'rack-ratelimit', github: 'jeremy/rack-ratelimit'
# gem 'rotp' <= 2FA
gem 'webauthn', '2.5.2'

# Storage
gem 'aws-sdk-s3', '1.115.0'
gem 'carrierwave', '2.2.2'
gem 'fog-aws', '3.15.0'
gem 'google-ads-googleads', '19.0.0'
gem 'google-apis-drive_v3', '0.30.0'
gem 'net-sftp', '4.0.0'

# Webserver
gem 'puma', '5.6.5'

# Other
gem 'active_model_serializers', '0.10.12'
gem 'awesome_print', '1.9.2'
gem 'breadcrumbs_on_rails', '4.1.0'
gem 'faraday', '1.10.2'
gem 'figaro', '1.2.0'
gem 'googleauth', '1.3.0'
gem 'jbuilder', '2.11.5'
gem 'kaminari', '1.2.2'
gem 'nokogiri', '1.13.9'
gem 'rack-cors', '1.1.1', :require => 'rack/cors'
gem 'savon', '2.13.1'
gem 'stimulus-rails', '1.1.0'
gem 'telephone_number', '1.4.9'
gem 'turbo-rails', '1.3.1'
gem 'validates_zipcode', '0.3.3'

# Temp locked
# # 2.8.0 gives errors. Is solved in 2.8.1.
gem 'mail', '2.7.1'
# This gem is a dependency of carrierwave. It's pinned to 1.0.8, because after that remote_..._url
# does not work. When this works again, this can be removed. If spec/features/pro/products/new_product_spec.rb
# is succesfull, this can be removed
gem 'ssrf_filter', '1.0.8'
# Need to pin this to 3.5.0 because savon doesn't work with any higher.
# Should start working again when this issue is solved:
# https://github.com/savonrb/savon/issues/935
gem 'wasabi', '3.5.0'

group :development, :test do
  gem 'byebug'
  gem 'break'

  # Code critics
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'brakeman', require: false
  gem 'benchmark-ips', require: false
end

group :development do
  gem 'faker'
  gem 'listen'
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'database_cleaner-active_record', '2.0.0'
  # Need to pin this to 2.0.0 because got foreign key errors with '2.0.1', remove this complete line
  # when working again, just try rspec, when no errors it works.
  gem 'factory_bot_rails'
  gem 'cuprite'
  gem 'rails-controller-testing'
  gem 'rubocop-rspec'
  gem 'rspec-rails', '5.0.1'
  gem 'rspec-retry', '0.6.2'
  gem 'rspec-wait'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
