source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.6'

gem 'rails', '8.1.1'
gem 'tzinfo-data', '>= 1.2024.2' # Don't rely on OSX/Linux timezone data

# Drivers
gem 'elasticsearch', '7.17.11'
gem 'hiredis-client', '0.26.1'
gem 'mini_magick', '4.13.2'
gem 'pg', '1.6.2'
gem 'redis', '5.4.1'

# CSS and Assets
gem 'autoprefixer-rails', '10.4.21.0'
gem 'bootstrap', '5.3.3' # TODO moving away from bootstrap to tailwind, remove
gem 'bootstrap_form', '5.5.0' # TODO moving away from bootstrap to tailwind, remove
gem 'bootstrap5-kaminari-views', '0.0.1' # TODO moving away from bootstrap to tailwind, remove
gem 'dartsass-rails', '0.5.1' # TODO remove once bootstrap migration complete
gem 'importmap-rails', '2.2.2'
gem 'inline_svg', '1.10.0'
gem 'propshaft', '1.3.1'
gem 'tailwindcss-rails', '4.4.0'
gem 'tailwindcss-ruby', '4.1.16'

# Jobs
gem 'active_scheduler', '0.7.0'
gem 'resque', '2.7.0'
gem 'resque-pool', '0.7.1'
gem 'resque-scheduler', '4.11.0'
gem 'sinatra', github: 'sinatra/sinatra'

# Logging/instrumentation
# gem 'full_request_logger', github: 'basecamp/full_request_logger'

# Monitoring
# gem 'sentry-raven', '3.1.1'

# Profiling/troubleshooting
gem 'rbtrace', '0.5.2'
gem 'stackprof', '0.2.27'
gem 'rack-mini-profiler', '4.0.1', require: false
gem 'flamegraph', '0.9.5'

# Security
gem 'devise', '4.9.4'
gem 'devise_invitable', '2.0.11'
# gem 'rack-ratelimit', github: 'jeremy/rack-ratelimit'
# gem 'rotp' <= 2FA
# gem 'webauthn', '3.2.2'

# Storage
gem 'carrierwave', '3.1.2'
gem 'fog-aws', '3.33.0'
gem 'net-ftp', '0.3.9'
gem 'net-sftp', '4.0.0'

# Webserver
gem 'puma', '6.6.1'

# AWS
gem 'aws-sdk-s3', '1.202.0'
gem 'aws-sdk-textract', '1.85.0'

# Google'
gem 'googleauth', '1.15.1'
gem 'google-ads-googleads', '36.0.0'
gem 'google-apis-drive_v3', '0.73.0'
gem 'google-cloud-document_ai', '2.0.2'
gem 'google-cloud-storage', '1.57.0'

# Other
gem 'active_model_serializers', '0.10.15'
gem 'awesome_print', '1.9.2'
gem 'breadcrumbs_on_rails', '4.1.0'
gem 'builder', '3.3.0'
gem 'csv', '3.3.5'
gem 'date_parser', '0.1.51'
gem 'faraday', '2.14.0'
gem 'faraday-digestauth', '0.4.1'
gem 'faraday-typhoeus', '1.1.0' # needed for ElasticSearch
gem 'figaro', '1.3.0'
gem 'jbuilder', '2.14.1'
gem 'kaminari', '1.2.2'
gem 'kramdown', '2.5.1'
gem 'maxmind-db', '1.3.2'
gem 'mimemagic', '0.4.3'
gem 'mime-types', '3.7.0'
gem 'mysql2', '0.5.7'
gem 'namae', '1.2.0'
gem 'nokogiri', '1.18.10'
gem 'openssl', '3.3.2'
gem 'postmark-rails', '0.22.1'
gem 'public_suffix', '6.0.2'
gem 'rack-cors', '1.1.1', require: 'rack/cors'
gem 'recaptcha', '5.21.1'
gem 'requestjs-rails', '0.0.13'
gem 'rest-client', '2.1.0'
gem 'restforce', '8.0.0'
gem 'ruby-openai', '7.4.0'
gem 'ruby_postal', '1.0.1', require: false
gem 'savon', '2.15.1'
gem 'stimulus-rails', '1.3.4'
gem 'stripe', '17.1.0'
gem 'telephone_number', '1.4.24'
gem 'turbo-rails', '2.0.20'
gem 'validates_zipcode', '0.5.4'

# Temp locked


group :development, :test do
  gem 'break'
  gem 'debug'
  gem 'faker'

  # Code critics
  gem 'benchmark-ips', require: false
  gem 'brakeman', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'cuprite', '0.15.1'
  gem 'rails-controller-testing'
  gem 'rubocop-rspec'
  gem 'rspec-rails', '7.1.1'
  gem 'rspec-retry', '0.6.2'
  gem 'rspec-wait'
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
