source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.0.3.4'

gem 'abanalyzer', '1.0.0'
gem 'active_model_serializers', '0.10.10'
gem 'active_scheduler', '0.7.0'
gem 'autoprefixer-rails', '10.0.1.0'
gem 'aws-sdk-s3', '1.83.0'
gem 'babel-transpiler', '0.7.0'
gem 'bootstrap_form', '4.5.0'
gem 'bootstrap4-kaminari-views', '1.0.1'
# gem 'bootstrap-sass', '3.1.1.0' # should be removed when iframe is completely gone
gem 'bourbon', '4.3.4' # should be removed when iframe is completely gone
gem 'breadcrumbs_on_rails', '4.0.0'
gem 'coffee-rails', '5.0.0'
gem 'devise', '4.7.3'
gem 'elasticsearch', '6.8.2'
gem 'faraday', '1.0.1'
gem 'figaro', '1.2.0'
gem 'fog-aws', '3.6.7'
gem 'hiredis', '0.6.3'
gem 'image_processing', '1.12.0'
gem 'jquery-rails', '4.4.0'
gem 'kaminari', '1.2.1'
gem 'mini_magick', '4.10.1'
gem 'nokogiri', '1.10.10'
gem 'octicons_helper', '3.0.1' # should be removed when iframe is completely gone
gem 'paperclip', '6.1.0' # deprecated, move to action storage
gem 'paperclip-compression', '1.1.1' # deprecated, move to action storage
gem 'pg', '1.2.3'
gem 'puma', '5.0.2'
gem 'rack-cors', '1.1.1', :require => 'rack/cors'
gem 'redis', '4.2.2', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.27.4'
gem 'resque-pool', '0.7.1'
gem 'resque-scheduler', '4.4.0'
gem 'sass-rails', '6.0.0'
gem 'savon', '2.12.1'
gem 'typhoeus', '1.4.0'
gem 'uglifier', '4.2.0'
gem 'webpacker', '5.2.1'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  # gem 'rack-mini-profiler', require: false
  gem 'rack_session_access'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'ruby-prof'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.1.5'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'cuprite'
  gem 'rails-controller-testing'
  gem 'rubocop-rspec'
  gem 'rspec-rails', '4.0.1'
  gem 'rspec-wait'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
