source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.1.4.1'
gem 'tzinfo-data', '>= 1.2020.6'  # Don't rely on OSX/Linux timezone data

# Drivers
gem 'hiredis', '0.6.3'
gem 'image_processing', '1.12.1'
gem 'mini_magick', '4.11.0'
gem 'pg', '1.2.3'
gem 'redis', '4.3.1', require: ['redis', 'redis/connection/hiredis']

# JavaScript and assets
gem 'autoprefixer-rails', '10.3.3.0'
gem 'bootstrap_form', '4.5.0'
gem 'bootstrap4-kaminari-views', '1.0.1'
gem 'sass-rails', '6.0.0'
gem 'webpacker', '5.4.0'

# Jobs
gem 'active_scheduler', '0.7.0'
gem 'resque', '2.0.0'
gem 'resque-pool', github: 'nevans/resque-pool'
gem 'resque-scheduler', '4.4.0'
gem 'sinatra', github: 'sinatra/sinatra'

# Monitoring
gem 'easymon', '1.4.2'

# Security
gem 'devise', '4.8.0'
gem 'webauthn', '2.5.0'

# Storage
gem 'aws-sdk-s3', '1.96.1'
gem 'carrierwave', '2.2.2'
gem 'fog-aws', '3.10.0'

# Webserver
gem 'puma', '5.3.2'

# Other
gem 'awesome_print', '1.9.2'
gem 'breadcrumbs_on_rails', '4.1.0'
gem 'faraday', '1.4.3'
gem 'figaro', '1.2.0'
gem 'hotwire-rails', '0.1.3'
gem 'kaminari', '1.2.1'
gem 'poppler', '3.4.9' # PDF rendering
gem 'tds_common_lib', github: 'TheDutchSelection/tds_common_lib'

group :development, :test do
  gem 'byebug'
  gem 'break'

  # Code critics
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'brakeman', require: false
  gem 'benchmark-ips', require: false
end

group :development do
  gem 'faker'
  gem 'listen'
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'database_cleaner-active_record', '2.0.0'
  # Need to pin this to 2.0.0 because got foreign key errors with '2.0.1', remove this complete line
  # when working again, just try rspec, when no errors it works.
  gem 'factory_bot_rails'
  gem 'cuprite'
  gem 'rails-controller-testing'
  gem 'rubocop-rspec'
  gem 'rspec-rails', '5.0.1'
  gem 'rspec-retry', '0.6.2'
  gem 'rspec-wait'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
