source 'https://rubygems.org'

ruby '2.3.3'

gem 'rails', '5.0.4'

gem 'active_model_serializers', '0.10.6'
gem 'autoprefixer-rails', '7.1.1.2'
gem 'bourbon', '4.3.4'
gem 'breadcrumbs_on_rails', '3.0.1'
gem 'coffee-rails', '4.2.2' # is always needed for rails
gem 'devise', '4.3.0'
gem 'faraday', '0.12.1'
gem 'figaro', '1.1.1'
gem 'fog-aws', '1.4.0'
gem 'hiredis', '0.6.1'
gem 'jquery-rails', '4.3.1'
gem 'kaminari', '1.0.1'
gem 'paperclip', '5.1.0'
gem 'paperclip-compression', '0.3.16'
gem 'pg', '0.21.0'
gem 'puma', '3.9.1'
gem 'rack-cors', '0.4.1', :require => 'rack/cors'
gem 'redis', '3.3.3', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.27.4'
gem 'resque-pool', '0.6.0'
gem 'resque-scheduler', '4.3.0'
gem 'sass-rails', '5.0.6'
gem 'simhanada', github: 'TheDutchSelection/simhanada_css', branch: 'master'
gem 'sinatra', '2.0.0'
gem 'sprockets-es6', '0.9.2'
gem 'uglifier', '3.2.0'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
  gem 'teaspoon-jasmine'
  gem 'guard-rspec', '~> 4.6', require: false
  gem 'guard-livereload', '~> 2.5.2', require: false
  gem 'guard-teaspoon'
  gem 'rack-livereload'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.6'
  gem 'terminal-notifier-guard'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'jasmine-rails'
  gem 'poltergeist'
  gem 'rspec-rails', '3.6.0'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
end
