source 'https://rubygems.org'

ruby '2.3.0'

gem 'rails', '5.0.0.beta3'

# gem 'active_model_serializers', '0.10.0.rc4'
gem 'autoprefixer-rails', '6.3.3.1'
gem 'bootstrap-sass', '3.3.6'
gem 'devise', '3.5.6'
gem 'figaro', '1.1.1'
gem 'fog', '1.37.0'
gem 'hiredis', '0.6.1'
gem 'jquery-rails'
gem 'pg', '0.18.4'
gem 'rack-cors', '0.4.0', :require => 'rack/cors'
#gem 'rails-api', '0.4.0'
gem 'redis', '3.2.2', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.26'
gem 'resque-pool', '0.6.0'
gem 'resque-scheduler', '4.1.0'
gem 'resque-web', '0.0.7', require: 'resque_web'
gem 'sass-rails', '5.0.4'
gem 'sprockets-es6', '0.9.0'
gem 'uglifier', '>= 2.7.1'
gem 'unicorn', '5.0.1'
gem 'will_paginate-bootstrap', '1.0.1'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'quiet_assets'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'unicorn-rails'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'listen', '~> 3.0.6'
  gem 'terminal-notifier-guard', '1.6.3'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'guard-rspec', '~> 4.6.0'
  gem 'jasmine-rails'
  gem 'poltergeist'
  gem 'rspec-rails'
  gem 'simplecov', :require => false
  gem 'vcr'
end