source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.0.3.4'
gem 'tzinfo-data', '>= 1.2020.6'  # Don't rely on OSX/Linux timezone data

# Drivers
gem 'hiredis', '0.6.3'
gem 'image_processing', '1.12.0'
gem 'mini_magick', '4.10.1'
gem 'pg', '1.2.3'
gem 'redis', '4.2.5', require: ['redis', 'redis/connection/hiredis']

# JavaScript and assets
gem 'autoprefixer-rails', '10.0.1.0'
gem 'bootstrap_form', '4.5.0'
gem 'bootstrap4-kaminari-views', '1.0.1'
gem 'sass-rails', '6.0.0'
gem 'webpacker', '5.2.1'

# Jobs
gem 'active_scheduler', '0.7.0'
gem 'resque', '2.0.0'
gem 'resque-pool', github: 'nevans/resque-pool'
gem 'resque-scheduler', '4.4.0'
gem 'resque-web', require: 'resque_web'
gem 'resque-scheduler-web', github: 'mattgibson/resque-scheduler-web'
gem 'sinatra', github: 'sinatra/sinatra'

# Logging/instrumentation
# gem 'full_request_logger', github: 'basecamp/full_request_logger'

# Monitoring
gem 'easymon', '1.4.2'
# gem 'sentry-raven', '3.1.1'

# Profiling/troubleshooting
gem 'rbtrace', '0.4.14'
gem 'stackprof', '0.2.16'
gem 'rack-mini-profiler', '2.3.0', require: false
gem 'flamegraph', '0.9.5'

# Security
gem 'devise', '4.7.3'
# gem 'rack-ratelimit', github: 'jeremy/rack-ratelimit'
# gem 'rotp' <= 2FA
gem 'webauthn'

# Storage
gem 'aws-sdk-s3', '1.83.0'
gem 'carrierwave', '2.1.0'
gem 'fog-aws', '3.6.7'

# Webserver
gem 'puma', '5.0.2'

# Other
gem 'breadcrumbs_on_rails', '4.0.0'
gem 'faraday', '1.0.1'
gem 'figaro', '1.2.0'
gem 'kaminari', '1.2.1'
gem 'tds_common_lib', github: 'TheDutchSelection/tds_common_lib'

group :development, :test do
  gem 'byebug'
  gem 'break'

  # Code critics
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'scss_lint', require: false
  gem 'brakeman', require: false
  gem 'benchmark-ips', require: false
end

group :development do
  gem 'faker'
  gem 'listen'
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'cuprite'
  gem 'rails-controller-testing'
  gem 'rubocop-rspec'
  gem 'rspec-rails', '4.0.1'
  gem 'rspec-wait'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
