source 'https://rubygems.org'

ruby '2.3.0'

gem 'rails', '5.0.0.rc2'

gem 'autoprefixer-rails', '6.3.6'
gem 'bourbon', '4.2.7'
gem 'coffee-rails', '4.1.1' # is always needed for rails
gem 'capybara', '2.7.1'
gem 'devise', '4.1.0'
gem 'faraday', '0.9.2'
gem 'figaro', '1.1.1'
gem 'fog', '1.38.0'
gem 'hiredis', '0.6.1'
gem 'jquery-rails', '4.1.1'
gem 'kaminari', '0.17.0'
gem 'nokogiri', '1.6.8'
gem 'paperclip', '4.3.6'
gem 'paperclip-compression', '0.3.15'
gem 'pg', '0.18.4'
gem 'poltergeist', '1.10.0'
gem 'puma', '3.4.0'
gem 'redis', '3.3.0', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.26'
gem 'resque-pool', '0.6.0'
gem 'resque-scheduler', '4.2.0'
gem 'sass-rails', '5.0.4'
gem 'simhanada', github: 'TheDutchSelection/simhanada_css', branch: 'master'
gem 'sinatra', github: 'sinatra/sinatra', branch: 'master' # waiting for sinatra >= 2, this is for resque, which depends on Sinatra
gem 'sprockets-es6', '0.9.0'
gem 'uglifier', '3.0.0'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'quiet_assets'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'teaspoon-jasmine'
  gem 'guard-rspec', '~> 4.6', require: false
  gem 'guard-livereload', '~> 2.5.2', require: false
  gem 'guard-teaspoon'
  gem 'rack-livereload'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.6'
  gem 'terminal-notifier-guard', '1.6.3'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'jasmine-rails'
  gem 'rspec', '~> 3.5.0.beta3'
  gem 'rspec-core', '~> 3.5.0.beta3'
  gem 'rspec-rails', '>= 3.5.0.beta3'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
end
