source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '5.0.1'

gem 'autoprefixer-rails', '6.7.2'
gem 'bourbon', '4.2.7'
gem 'breadcrumbs_on_rails', '3.0.1'
gem 'coffee-rails', '4.2.1' # is always needed for rails
gem 'capybara', '2.12.0'
gem 'devise', '4.2.0'
gem 'faraday', '0.11.0'
gem 'figaro', '1.1.1'
gem 'fog', '1.38.0'
gem 'hiredis', '0.6.1'
gem 'jquery-rails', '4.2.1'
gem 'kaminari', '1.0.1'
gem 'nokogiri', '1.7.0.1'
gem 'paperclip', '4.3.7'
gem 'paperclip-compression', '0.3.15'
gem 'pg', '0.19.0'
gem 'poltergeist', '1.13.0'
gem 'puma', '3.7.0'
gem 'redis', '3.3.2', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.26'
gem 'resque-pool', '0.6.0'
gem 'resque-scheduler', '4.3.0'
gem 'sass-rails', '5.0.6'
gem 'simhanada', github: 'TheDutchSelection/simhanada_css', branch: 'master'
gem 'sinatra', github: 'sinatra/sinatra', branch: 'master' # waiting for sinatra >= 2, this is for resque, which depends on Sinatra
gem 'sprockets-es6', '0.9.2'
gem 'uglifier', '3.0.4'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
  gem 'teaspoon-jasmine'
  gem 'guard-rspec', '~> 4.6', require: false
  gem 'guard-livereload', '~> 2.5.2', require: false
  gem 'guard-teaspoon'
  gem 'rack-livereload'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.6'
  gem 'terminal-notifier-guard', '1.6.3'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'jasmine-rails'
  gem 'rspec-rails', '3.5.2'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
end
