source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '5.0.0'

gem 'bootstrap-sass', '3.3.6'
gem 'coffee-rails', '4.1.1'
gem 'figaro', '1.1.1'
gem 'jquery-rails', '4.1.1'
gem 'pg', '0.18.4'
gem 'puma', '3.4.0'
gem 'sass-rails', '5.0.5'
gem 'sprockets-es6', '0.9.0'
gem 'uglifier', '3.0.0'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'listen', '~> 3.0.6'
  gem 'terminal-notifier-guard', '1.6.3'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'jasmine-rails'
  gem 'letter_opener'
  gem 'poltergeist'
  gem 'rspec-rails', '>= 3.5.1'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
end
