source 'https://rubygems.org'

ruby '2.4.1'

gem 'rails', '5.0.7'

gem 'active_model_serializers', '0.10.7'
gem 'active_scheduler', '0.5.0'
gem 'autoprefixer-rails', '8.4.1'
gem 'bourbon', '4.3.4'
gem 'breadcrumbs_on_rails', '3.0.1'
gem 'coffee-rails', '4.2.2' # is always needed for rails
gem 'devise', '4.4.3'
gem 'faraday', '0.15.0'
gem 'figaro', '1.1.1'
gem 'fog-aws', '3.0.0'
gem 'hiredis', '0.6.1'
gem 'jquery-rails', '4.3.3'
gem 'kaminari', '1.1.1'
gem 'paperclip', '6.0.0'
gem 'paperclip-compression', '1.0.1'
gem 'pg', '1.0.0'
gem 'puma', '4.3.1'
gem 'rack-cors', '1.0.2', require: 'rack/cors'
gem 'redis', '3.3.5', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '1.27.4'
gem 'resque-pool', '0.6.0'
gem 'resque-scheduler', '4.3.1'
gem 'sass-rails', '5.0.7'
gem 'simhanada', github: 'TheDutchSelection/simhanada_css', branch: 'master'
gem 'sinatra', '2.0.1'
gem 'sprockets-es6', '0.9.2'
gem 'uglifier', '4.1.10'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
  gem 'teaspoon-jasmine'
  gem 'guard-rspec', '~> 4.6', require: false
  gem 'guard-livereload', '~> 2.5.2', require: false
  gem 'guard-teaspoon'
  gem 'rack-livereload'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.6'
  gem 'terminal-notifier-guard'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'jasmine-rails'
  gem 'poltergeist'
  gem 'rspec-rails', '3.7.1'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
end
