source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.1.4.1'
gem 'tzinfo-data', '>= 1.2020.6'  # Don't rely on OSX/Linux timezone data

# Drivers
gem 'pg', '1.2.3'

# JavaScript and assets
gem 'autoprefixer-rails', '10.3.3.0'
gem 'bootstrap_form', '4.5.0'
gem 'sass-rails', '6.0.0'
gem 'webpacker', '5.4.0'

# Monitoring
gem 'easymon', '1.4.2'

# Profiling/troubleshooting
gem 'rbtrace', '0.4.14'
gem 'stackprof', '0.2.17'
gem 'rack-mini-profiler', '2.3.3', require: false
gem 'flamegraph', '0.9.5'

# Webserver
gem 'puma', '5.3.2'

# Other
gem 'faraday', '1.4.3'
gem 'figaro', '1.2.0'
gem 'hotwire-rails', '0.1.3'
gem 'recaptcha', '5.6.0'

group :development, :test do
  gem 'byebug'
  gem 'break'

  # Code critics
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'brakeman', require: false
  gem 'benchmark-ips', require: false
end

group :development do
  gem 'faker'
  gem 'listen'
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'database_cleaner-active_record', '2.0.0'
  # Need to pin this to 2.0.0 because got foreign key errors with '2.0.1', remove this complete line
  # when working again, just try rspec, when no errors it works.
  gem 'factory_bot_rails'
  gem 'cuprite'
  gem 'rails-controller-testing'
  gem 'rubocop-rspec'
  gem 'rspec-rails', '5.0.1'
  gem 'rspec-retry', '0.6.2'
  gem 'rspec-wait'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
