source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.0.3.2'

gem 'bootstrap_form', '4.5.0'
gem 'faraday', '1.0.1'
gem 'figaro', '1.1.1'
gem 'pg', '1.2.3'
gem 'puma', '4.3.5'
gem 'sass-rails', '6.0.0'
gem 'webpacker', '5.2.1'


group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails', '6.1.0'
  gem 'poltergeist', '1.18.1'
  gem 'rspec-rails', '4.0.1'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
