source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'rails', '5.2.3'

gem 'active_scheduler', '0.5.0'
gem 'breadcrumbs_on_rails', '3.0.1'
gem 'faraday', '0.15.4'
gem 'figaro', '1.1.1'
gem 'hiredis', '0.6.3'
gem 'maxmind-db', '1.0.0'
gem 'puma', '3.12.4'
gem 'redis', '4.1.0', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '2.0.0'
gem 'resque-pool', git: 'https://github.com/nevans/resque-pool.git', branch: 'master' # we need version after 0.6.0
gem 'resque-scheduler', git: 'https://github.com/resque/resque-scheduler.git', branch: 'master' # we need version after 4.3.1
gem 'sass-rails', '5.0.7'
gem 'sprockets-es6', '0.9.2'
gem 'pg', '1.1.4'
gem 'uglifier', '4.1.20'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails', '5.0.2'
  gem 'poltergeist', '1.18.1'
  gem 'rspec-rails', '3.8.2'
  gem 'timecop'
  gem 'vcr'
end
