source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'rails', '6.0.2.2'

gem 'active_scheduler', '0.6.0'
gem 'breadcrumbs_on_rails', '4.0.0'
gem 'faraday', '1.0.1'
gem 'figaro', '1.1.1'
gem 'hiredis', '0.6.3'
gem 'maxmind-db', '1.1.0'
gem 'pg', '1.2.3'
gem 'puma', '4.3.3'
gem 'redis', '4.1.3', require: ["redis", "redis/connection/hiredis"]
gem 'resque', '2.0.0'
gem 'resque-pool', '0.7.1'
gem 'resque-scheduler', '4.4.0'
gem 'sass-rails', '6.0.0'
gem 'webpacker', '4.2.2'

group :development, :test do
  gem 'debase'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack_session_access'
  gem 'ruby-debug-ide'
end

group :development do
  gem 'web-console'
  gem 'listen'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails', '5.1.1'
  gem 'poltergeist', '1.18.1'
  gem 'rspec-rails', '4.0.0'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
