source 'https://rubygems.org'

ruby '2.4.1'

gem 'rails', '5.1.2'

gem 'figaro', '1.1.1'
gem 'pg', '0.21.0'
gem 'puma', '3.9.1'
gem 'sass-rails', '5.0.6'
gem 'sprockets-es6', '0.9.2'
gem 'uglifier', '3.2.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'poltergeist'
  gem 'rspec-rails', '3.6.0'
  gem 'simplecov', :require => false
end